// this source is generated by the class "Tuple generator"

package com.aparigraha.tuple.extensions.stream;

import java.util.List;
import java.util.stream.Stream;


import com.aparigraha.tuple.extensions.stream.Zipper;


public record StudentInfo<T0, T1, T2, T3> (T0 id, T1 name, T2 age, T3 isDayScholar) {
    @Override
    public boolean equals(Object obj) {
        if (obj instanceof StudentInfo<?, ?, ?, ?> that) {
            return this.id == that.id && this.name == that.name && this.age == that.age && this.isDayScholar == that.isDayScholar;
        } else return false;
    }


    public static <T0, T1, T2, T3> Stream<StudentInfo<T0, T1, T2, T3>> zip(Stream<T0> stream0, Stream<T1> stream1, Stream<T2> stream2, Stream<T3> stream3) {
        List<Stream<Object>> streams = List.of((Stream<Object>) stream0, (Stream<Object>) stream1, (Stream<Object>) stream2, (Stream<Object>) stream3);
        return Zipper.zip(streams).map(zipped -> new StudentInfo<>((T0) zipped.get(0), (T1) zipped.get(1), (T2) zipped.get(2), (T3) zipped.get(3)));
    }
}